# Generated by Django 5.2.12 on 2026-03-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0002_orderassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
